# Cenários que falharam na evolução
20
174,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:19:15.397,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2418021,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
112,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:05:37.051,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1561728,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
195,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:24:30.642,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2750206,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
156,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:16:23.687,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2295303,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
201,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:26:02.932,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2864857,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
239,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:33:47.485,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3330017,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
160,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:16:52.235,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2313348,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
236,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:32:49.516,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3244593,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
16,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 19:44:26.035,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
223723,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
60,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 19:54:11.332,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
872650,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
126,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:08:35.172,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1753035,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
4,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 19:42:08.099,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
101229,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
178,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:20:28.327,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2522463,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
51,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 19:53:16.763,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
855837,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
129,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:08:42.317,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1754422,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
48,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 19:51:14.054,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
667390,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
83,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:00:27.437,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1299583,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
107,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-04 20:03:29.177,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1374935,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
44,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 19:50:51.465,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
665480,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
87,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-04 20:00:51.851,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1302840,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
