# Cenários que falharam na primeira versão
20
105,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:13:26.156,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
4527,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
130,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:15:20.254,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
5567,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
78,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:10:20.484,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3308,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
131,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:15:22.002,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
5575,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
63,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:08:36.619,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2650,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
61,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:08:32.407,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2626,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
186,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:19:44.098,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
8036,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
14,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:02:53.731,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
585,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
83,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:10:45.039,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3484,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
222,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:23:29.783,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
9612,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
29,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:04:51.339,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1234,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
231,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:24:18.892,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
9965,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
167,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:18:13.352,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
7191,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
45,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:07:10.055,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1928,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
12,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:02:51.266,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
566,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
123,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:14:49.85,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
5308,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
216,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:23:03.216,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
9333,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
184,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:19:39.839,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
7963,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
241,Entry point for SctpEchoTest.testSimpleEcho,1,2014-04-29 02:24:55.381,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
10355,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
162,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-04-29 02:17:56.785,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
7056,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
