# Cenários que falharam na primeira versão
20
233,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 14:17:50.778,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3807451,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
58,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:30:32.4,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
917480,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
213,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 14:12:23.926,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3415111,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
97,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:41:24.512,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1466699,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
114,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:46:48.041,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1840828,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
187,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 14:05:55.704,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3018667,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
130,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:51:49.745,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2207093,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
9,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:17:54.098,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
21384,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
34,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:25:31.444,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
629670,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
155,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:57:52.103,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2594210,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
71,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:35:20.953,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1057113,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
165,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 14:00:28.509,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2638689,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
205,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 14:11:32.352,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3409187,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
26,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:22:59.983,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
408274,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
12,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 13:19:05.608,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
138203,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
128,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:51:46.657,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2206624,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
73,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:35:26.881,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1058052,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
194,Entry point for SctpEchoTest.testSimpleEcho,1,2014-05-03 14:08:01.955,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3146867,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
66,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:34:02.61,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
952669,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
162,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-05-03 13:59:57.231,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2622267,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
