# Cenários que falharam na primeira versão
10
527,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 07:04:06.141,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
16937827,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
572,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 07:24:03.927,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
18083304,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
88,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 03:37:01.734,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2789205,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
345,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 05:42:54.939,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
11538583,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
404,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 06:04:45.31,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
12798166,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
14,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 02:59:50.431,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
142718,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
595,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 07:39:10.195,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
19061296,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
303,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 05:13:23.775,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
9146269,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
250,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 04:46:05.616,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
7147656,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
147,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-07 04:05:34.274,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
4771211,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
